# Generated by Django 5.1.4 on 2025-01-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicID', models.IntegerField()),
                ('CommentNumber', models.IntegerField()),
                ('CommenterName', models.CharField(max_length=255)),
                ('CommentText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicID', models.IntegerField()),
                ('TopicName', models.CharField(max_length=255)),
                ('TopicDescription', models.CharField(max_length=255)),
                ('TopicPublishedDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
