# Generated by Django 5.1.4 on 2025-01-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_comments_post_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='TopicName',
            new_name='PostName',
        ),
    ]
