# Generated by Django 5.1.4 on 2025-01-18 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_rename_topicname_post_postname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentNumber', models.IntegerField()),
                ('CommenterName', models.CharField(max_length=255)),
                ('CommentText', models.CharField(max_length=255)),
                ('TopicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
